services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NEXTCLOUD_ADMIN_USER=zefuros
      - NEXTCLOUD_ADMIN_PASSWORD=!REg7hQNMWbRHECg.s@n2ZneKbXxENaYiuJ6XA
      - NEXTCLOUD_TRUSTED_DOMAINS=.nextcloud.zecuritylabs.com
    volumes:
      - nextcloud_data:/var/www/html/

volumes:
  nextcloud_data:
    name: nextcloud_data
networks:
  proxy:
    external: true