services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    networks:
      - proxy
  
    volumes:
      - homarr:/app/data/configs
      - homarr:/app/public/icons
      - homarr:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  proxy:
    external: true
volumes:
  homarr: