services:
  adguard:
    image: adguard/adguardhome:latest  # Image to use for AdGuardHome service
    container_name: adguard          # Name of the Docker container
    networks:
      - exampleproxybridge        # Network that this service will connect to (We are using exampleproxybridge as example from phase 3. Networks)
    ports:
      - "53:53/tcp"              # Port mapping for DNS over TCP (default port 53)
      - "53:53/udp"              # Port mapping for DNS over UDP (default port 53)
      - "80:80/tcp"              # Port mapping for HTTP traffic (default port 80) (we will later delete this line)
      - "3000:3000/tcp"          # Port mapping for the AdGuard Home management interface (we will later delete this line)
    volumes:
      - adguard_work:/opt/adguardhome/work  # Volume for AdGuardHome work directory
      - adguard_conf:/opt/adguardhome/conf  # Volume for AdGuardHome configuration files
    environment:
      - TZ=         # Configure the timezone (format: 'Continent/City')
    restart: unless-stopped       # Restart policy, container will always start unless stopped manually

# Named volumes are created within the service definitions to manage them through Docker Compose.
volumes:
  adguard_work:  # Volume for AdGuardHome work directory
  adguard_conf:  # Volume for AdGuardHome configuration files

networks:
  exampleproxybridge:           # Define a network named 'exampleproxybridge'
    external: true              # Use an existing network or create one if it doesn't exist
